swagger: '2.0'
info:
  title: Luna.Gallery.Functions
  version: V1
host: localhost:7071
schemes:
  - http
paths:
  '/api/applicationpublishers/{name}':
    put:
      tags:
        - Applicaton Publisher
      summary: Register a publisher
      operationId: putApiApplicationpublishersByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - Applicaton Publisher
      summary: Update a publisher
      operationId: patchApiApplicationpublishersByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - Applicaton Publisher
      summary: Delete a publisher
      operationId: deleteApiApplicationpublishersByName
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
    get:
      tags:
        - Applicaton Publisher
      summary: Get a publisher
      operationId: getApiApplicationpublishersByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      security:
        - x-functions-key: [ ]
  /api/applicationpublishers:
    get:
      tags:
        - Applicaton Publisher
      summary: List publishers
      operationId: getApiApplicationpublishers
      produces:
        - application/json
      parameters:
        - in: query
          name: type
          description: Type of the publisher
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
            example:
              Name: ace
              DisplayName: ACE team
              Type: Internal
              Description: Azure Customer Engineering Team
              EndpointUrl: https://aka.ms/aceendpoint
              WebsiteUrl: https://aka.ms/acewebsite
              IsEnabled: true
              PublisherKey: publisher-key
              CreatedTime: 
              LastUpdatedTime: 
      security:
        - x-functions-key: [ ]
  /api/applications:
    get:
      tags:
        - Application
      summary: List published applications
      operationId: getApiApplications
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.PublishedLunaApplication'
            example:
              UniqueName: mylunaapp
              DisplayName: My Luna App
              Description: This is my Luna app
              LogoImageUrl: https://aka.ms/lunalog.png
              DocumentationUrl: https://aka.ms/lunadoc
              Publisher: Microsoft
              Tags: [ ]
              Details:
                APIs: [ ]
      security:
        - x-functions-key: [ ]
  '/api/applications/{name}/recommended':
    get:
      tags:
        - Application
      summary: Get recommended Luna applications
      operationId: getApiApplicationsByNameRecommended
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.PublishedLunaApplication'
            example:
              UniqueName: mylunaapp
              DisplayName: My Luna App
              Description: This is my Luna app
              LogoImageUrl: https://aka.ms/lunalog.png
              DocumentationUrl: https://aka.ms/lunadoc
              Publisher: Microsoft
              Tags: [ ]
              Details:
                APIs: [ ]
      security:
        - x-functions-key: [ ]
  '/api/applications/{name}':
    get:
      tags:
        - Application
      summary: Get a published Luna application
      operationId: getApiApplicationsByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.PublishedLunaApplication'
      security:
        - x-functions-key: [ ]
  '/api/applications/{name}/swagger':
    get:
      tags:
        - Application
      summary: Get swagger in JSON format for a published Luna application
      operationId: getApiApplicationsByNameSwagger
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
      responses:
        '200':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions/{subscriptionName}':
    put:
      tags:
        - Subscription
      summary: Create a subscription of a published Luna application
      operationId: putApiApplicationsByAppNameSubscriptionsBySubscriptionName
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionName
          description: Name of the subscription
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscription'
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions':
    get:
      tags:
        - Subscription
      summary: List all subscriptions of a published Luna application
      operationId: getApiApplicationsByAppNameSubscriptions
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the caller
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscription'
            example:
              SubscriptionId: 0eb1e9dd-df4e-4b03-9e8f-6d8ac0eab782
              SubscriptionName: mysub
              PrimaryKey: 60158cd36c464531bf40a6c7efc629cd
              SecondaryKey: fc7cfaab23b0494aa53f178f7fbc720c
              BaseUrl: https://luna.azurewebapp.net/api
              Notes: this is my subscription
              Owners:
                - UserId: c4627f84-c3a8-45b3-8709-565bd2e50b97
                  UserName: FirstName LastName
              CreatedTime: '2021-06-10T18:00:30.1320267-07:00'
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions/{subscriptionNameOrId}':
    get:
      tags:
        - Subscription
      summary: Get a subscription of a published Luna application
      operationId: getApiApplicationsByAppNameSubscriptionsBySubscriptionNameOrId
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscription'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - Subscription
      summary: Delete a subscription of a published Luna application
      operationId: deleteApiApplicationsByAppNameSubscriptionsBySubscriptionNameOrId
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions/{subscriptionNameOrId}/UpdateNotes':
    post:
      tags:
        - Subscription
      summary: Update notes of a subscription
      operationId: postApiApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdUpdateNotes
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionNotes'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionNotes'
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions/{subscriptionNameOrId}/AddOwner':
    post:
      tags:
        - Subscription
      summary: Add owner to a subscription
      operationId: postApiApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdAddOwner
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions/{subscriptionNameOrId}/RegenerateKey':
    post:
      tags:
        - Subscription
      summary: Regenerate a subscription key
      operationId: postApiApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdRegenerateKey
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: query
          name: key-name
          description: The name of the key. Either PrimaryKey or SecondaryKey
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionKeys'
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/subscriptions/{subscriptionNameOrId}/RemoveOwner':
    post:
      tags:
        - Subscription
      summary: Remove owner to a subscription
      operationId: postApiApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdRemoveOwner
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: header
          name: Luna-User-Id
          description: The user id of the creator
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      security:
        - x-functions-key: [ ]
definitions:
  Luna.Gallery.Public.Client.ApplicationPublisher:
    required:
      - Name
      - DisplayName
      - Type
      - Description
      - IsEnabled
    type: object
    properties:
      Name:
        type: string
      DisplayName:
        type: string
      Type:
        type: string
      Description:
        type: string
      EndpointUrl:
        type: string
      WebsiteUrl:
        type: string
      IsEnabled:
        type: boolean
      PublisherKey:
        type: string
      CreatedTime:
        format: date-time
        type: string
      LastUpdatedTime:
        format: date-time
        type: string
    example:
      Name: ace
      DisplayName: ACE team
      Type: Internal
      Description: Azure Customer Engineering Team
      EndpointUrl: https://aka.ms/aceendpoint
      WebsiteUrl: https://aka.ms/acewebsite
      IsEnabled: true
      PublisherKey: publisher-key
      CreatedTime: 
      LastUpdatedTime: 
  Luna.Gallery.Public.Client.PublishedLunaApplication:
    required:
      - UniqueName
      - DisplayName
      - Description
      - Publisher
      - Tags
    type: object
    properties:
      UniqueName:
        type: string
      DisplayName:
        type: string
      Description:
        type: string
      LogoImageUrl:
        type: string
      DocumentationUrl:
        type: string
      Publisher:
        type: string
      Tags:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaPublishedApplicationTag'
      Details:
        $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationDetails'
    example:
      UniqueName: mylunaapp
      DisplayName: My Luna App
      Description: This is my Luna app
      LogoImageUrl: https://aka.ms/lunalog.png
      DocumentationUrl: https://aka.ms/lunadoc
      Publisher: Microsoft
      Tags: [ ]
      Details:
        APIs: [ ]
  Luna.Gallery.Public.Client.LunaPublishedApplicationTag:
    type: object
    properties:
      Name:
        type: string
      Value:
        type: string
  Luna.Gallery.Public.Client.LunaApplicationDetails:
    type: object
    properties:
      APIs:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaAPIDetails'
  Luna.Gallery.Public.Client.LunaAPIDetails:
    type: object
    properties:
      Name:
        type: string
      Type:
        type: string
      Versions:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaAPIVersionDetails'
  Luna.Gallery.Public.Client.LunaAPIVersionDetails:
    type: object
    properties:
      Name:
        type: string
      Operations:
        type: array
        items:
          type: string
  Luna.Gallery.Public.Client.LunaApplicationSubscription:
    required:
      - SubscriptionId
      - SubscriptionName
    type: object
    properties:
      SubscriptionId:
        format: uuid
        type: string
        example: 00000000-0000-0000-0000-000000000000
      SubscriptionName:
        type: string
      PrimaryKey:
        type: string
      SecondaryKey:
        type: string
      BaseUrl:
        type: string
      Notes:
        type: string
      Owners:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      CreatedTime:
        format: date-time
        type: string
    example:
      SubscriptionId: 0eb1e9dd-df4e-4b03-9e8f-6d8ac0eab782
      SubscriptionName: mysub
      PrimaryKey: 60158cd36c464531bf40a6c7efc629cd
      SecondaryKey: fc7cfaab23b0494aa53f178f7fbc720c
      BaseUrl: https://luna.azurewebapp.net/api
      Notes: this is my subscription
      Owners:
        - UserId: c4627f84-c3a8-45b3-8709-565bd2e50b97
          UserName: FirstName LastName
      CreatedTime: '2021-06-10T18:00:30.1320267-07:00'
  Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner:
    required:
      - UserId
    type: object
    properties:
      UserId:
        type: string
      UserName:
        type: string
    example:
      UserId: 2d88c6a1-8ece-49e8-8b23-673c6a4272d2
      UserName: FirstName LastName
  Luna.Gallery.Public.Client.LunaApplicationSubscriptionNotes:
    required:
      - Notes
    type: object
    properties:
      Notes:
        type: string
    example:
      Notes: this is my subscription
  Luna.Gallery.Public.Client.LunaApplicationSubscriptionKeys:
    required:
      - PrimaryKey
      - SecondaryKey
    type: object
    properties:
      PrimaryKey:
        type: string
      SecondaryKey:
        type: string
    example:
      PrimaryKey: 3cbeda43ef6b4dc0b61220fbb2f7dda4
      SecondaryKey: fc7cfaab23b0494aa53f178f7fbc720c
securityDefinitions:
  x-functions-key:
    type: apiKey
    name: x-functions-key
    in: header
    description: Azure function key