swagger: '2.0'
info:
  title: Luna.Gateway.Functions
  version: V1
host: localhost:7071
schemes:
  - http
paths:
  /api/marketplace/subscriptions/resolveToken:
    post:
      tags:
        - Azure Marketplace
      summary: Resolve Azure Marketplace subscription from token
      operationId: postApiMarketplaceSubscriptionsResolveToken
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionResponse'
      security:
        - x-functions-key: [ ]
  '/api/marketplace/subscriptions/{subscriptionId}':
    put:
      tags:
        - Azure Marketplace
      summary: Create Azure Marketplace subscription
      operationId: putApiMarketplaceSubscriptionsBySubscriptionId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: subscriptionId
          description: ID of the subscription
          required: true
          type: string
        - in: body
          name: body
          description: The subscription
          required: true
          schema:
            $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionResponse'
      security:
        - x-functions-key: [ ]
    get:
      tags:
        - Azure Marketplace
      summary: Get Azure Marketplace subscription
      operationId: getApiMarketplaceSubscriptionsBySubscriptionId
      produces:
        - application/json
      parameters:
        - in: path
          name: subscriptionId
          description: ID of the subscription
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionResponse'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - Azure Marketplace
      summary: Delete Azure Marketplace subscription
      operationId: deleteApiMarketplaceSubscriptionsBySubscriptionId
      parameters:
        - in: path
          name: subscriptionId
          description: ID of the subscription
          required: true
          type: string
      responses:
        '200':
          description: Success
      security:
        - x-functions-key: [ ]
  /api/marketplace/subscriptions:
    get:
      tags:
        - Azure Marketplace
      summary: List Azure Marketplace subscriptions
      operationId: getApiMarketplaceSubscriptions
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionResponse'
      security:
        - x-functions-key: [ ]
  /api/marketplace/subscriptiondetails:
    get:
      tags:
        - Azure Marketplace
      summary: List Azure Marketplace subscription details
      operationId: getApiMarketplaceSubscriptiondetails
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionResponse'
      security:
        - x-functions-key: [ ]
  '/api/marketplace/offers/{offerId}/plans/{planId}/parameters':
    get:
      tags:
        - Gallery
      summary: Get offer parameters
      operationId: getApiMarketplaceOffersByOfferIdPlansByPlanIdParameters
      produces:
        - application/json
      parameters:
        - in: path
          name: offerId
          description: The offer ID
          required: true
          type: string
        - in: path
          name: planId
          description: The plan ID
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceParameter'
            example:
              ParameterName: region
              DisplayName: Region
              Description: The Azure region where resources are deployed to.
              ValueType: String
              FromList: true
              ValueList: westus;eastus
              Maximum: 0
              Minimum: 0
              IsRequired: false
              isUserInput: false
              defaultValue: 
      security:
        - x-functions-key: [ ]
  '/api/gallery/applications/{appName}':
    get:
      tags:
        - ML Gallery
      summary: Get a published Luna application
      operationId: getApiGalleryApplicationsByAppName
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: The name of the application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.PublishedLunaApplication'
      security:
        - http-bearer: [ ]
  /api/gallery/applications:
    get:
      tags:
        - ML Gallery
      summary: List published Luna applications
      operationId: getApiGalleryApplications
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.PublishedLunaApplication'
            example:
              UniqueName: mylunaapp
              DisplayName: My Luna App
              Description: This is my Luna app
              LogoImageUrl: https://aka.ms/lunalog.png
              DocumentationUrl: https://aka.ms/lunadoc
              Publisher: Microsoft
              Tags: [ ]
              Details:
                APIs: [ ]
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/swagger':
    get:
      tags:
        - ML Gallery
      summary: Get swagger of a published Luna application
      operationId: getApiGalleryApplicationsByAppNameSwagger
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: The name of the application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSwagger'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/recommended':
    get:
      tags:
        - ML Gallery
      summary: Get recommended applications for the specified Luna application
      operationId: getApiGalleryApplicationsByAppNameRecommended
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: The name of the application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.PublishedLunaApplication'
            example:
              UniqueName: mylunaapp
              DisplayName: My Luna App
              Description: This is my Luna app
              LogoImageUrl: https://aka.ms/lunalog.png
              DocumentationUrl: https://aka.ms/lunadoc
              Publisher: Microsoft
              Tags: [ ]
              Details:
                APIs: [ ]
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions/{subscriptionName}':
    put:
      tags:
        - ML Gallery
      summary: Create a subscription of a published Luna application
      operationId: putApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionName
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of the Luna application
          required: true
          type: string
        - in: path
          name: subscriptionName
          description: Name of the subscription
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscription'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions/{subscriptionNameOrId}':
    delete:
      tags:
        - ML Gallery
      summary: Delete a subscription of a published Luna application
      operationId: deleteApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionNameOrId
      parameters:
        - in: path
          name: appName
          description: Name of the Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - http-bearer: [ ]
    get:
      tags:
        - ML Gallery
      summary: Get a subscription of Luna application
      operationId: getApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionNameOrId
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: The name of the application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscription'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions':
    get:
      tags:
        - ML Gallery
      summary: List all subscription of a Luna application for current user
      operationId: getApiGalleryApplicationsByAppNameSubscriptions
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: The name of the application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscription'
            example:
              SubscriptionId: 0eb1e9dd-df4e-4b03-9e8f-6d8ac0eab782
              SubscriptionName: mysub
              PrimaryKey: 60158cd36c464531bf40a6c7efc629cd
              SecondaryKey: fc7cfaab23b0494aa53f178f7fbc720c
              BaseUrl: https://luna.azurewebapp.net/api
              Notes: this is my subscription
              Owners:
                - UserId: c4627f84-c3a8-45b3-8709-565bd2e50b97
                  UserName: FirstName LastName
              CreatedTime: '2021-06-10T18:00:30.1320267-07:00'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions/{subscriptionNameOrId}/addOwner':
    post:
      tags:
        - ML Gallery
      summary: Add a owner to the specified subscription
      operationId: postApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdAddOwner
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of the Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions/{subscriptionNameOrId}/removeOwner':
    post:
      tags:
        - ML Gallery
      summary: Remove a owner from the specified subscription
      operationId: postApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdRemoveOwner
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of the Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions/{subscriptionNameOrId}/regenerateKey':
    post:
      tags:
        - ML Gallery
      summary: Regenerate key for the specified subscription
      operationId: postApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdRegenerateKey
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of the Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: query
          name: key-name
          description: Name of the key
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionKeys'
      security:
        - http-bearer: [ ]
  '/api/gallery/applications/{appName}/subscriptions/{subscriptionNameOrId}/updatenotes':
    post:
      tags:
        - ML Gallery
      summary: Update notes for the specified subscription
      operationId: postApiGalleryApplicationsByAppNameSubscriptionsBySubscriptionNameOrIdUpdatenotes
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of the Luna application
          required: true
          type: string
        - in: path
          name: subscriptionNameOrId
          description: Name or id of the subscription
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionNotes'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionNotes'
      security:
        - http-bearer: [ ]
  '/api/gallery/applicationpublishers/{name}':
    put:
      tags:
        - ML Gallery
      summary: Register a publisher
      operationId: putApiGalleryApplicationpublishersByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - ML Gallery
      summary: Update a publisher
      operationId: patchApiGalleryApplicationpublishersByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - ML Gallery
      summary: Delete a publisher
      operationId: deleteApiGalleryApplicationpublishersByName
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
    get:
      tags:
        - ML Gallery
      summary: Get a publisher
      operationId: getApiGalleryApplicationpublishersByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
      security:
        - x-functions-key: [ ]
  /api/gallery/applicationpublishers:
    get:
      tags:
        - ML Gallery
      summary: List publishers
      operationId: getApiGalleryApplicationpublishers
      produces:
        - application/json
      parameters:
        - in: query
          name: type
          description: Type of the publisher
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Gallery.Public.Client.ApplicationPublisher'
            example:
              Name: ace
              DisplayName: ACE team
              Type: Internal
              Description: Azure Customer Engineering Team
              EndpointUrl: https://aka.ms/aceendpoint
              WebsiteUrl: https://aka.ms/acewebsite
              IsEnabled: true
              PublisherKey: publisher-key
              CreatedTime: 
              LastUpdatedTime: 
      security:
        - x-functions-key: [ ]
definitions:
  Luna.Marketplace.Public.Client.MarketplaceSubscriptionResponse:
    required:
      - id
      - publisherId
      - offerId
      - name
      - planId
      - createdTime
      - lastUpdatedTime
    type: object
    properties:
      id:
        format: uuid
        type: string
        example: 00000000-0000-0000-0000-000000000000
      publisherId:
        type: string
      offerId:
        type: string
      name:
        type: string
      saaSSubscriptionStatus:
        type: string
      planId:
        type: string
      allowedCustomerOperations:
        type: array
        items:
          type: string
      parameters:
        type: array
        items:
          $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionParameterResponse'
      createdTime:
        format: date-time
        type: string
      lastUpdatedTime:
        format: date-time
        type: string
      unsubscribedTime:
        format: date-time
        type: string
  Luna.Marketplace.Public.Client.MarketplaceSubscriptionParameterResponse:
    required:
      - name
      - type
      - value
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      value:
        type: string
  Luna.Marketplace.Public.Client.MarketplaceSubscriptionRequest:
    required:
      - id
      - publisherId
      - offerId
      - name
      - planId
      - ownerId
    type: object
    properties:
      id:
        format: uuid
        type: string
        example: 00000000-0000-0000-0000-000000000000
      publisherId:
        type: string
      offerId:
        type: string
      name:
        type: string
      planId:
        type: string
      ownerId:
        type: string
      token:
        type: string
      inputParameters:
        type: array
        items:
          $ref: '#/definitions/Luna.Marketplace.Public.Client.MarketplaceSubscriptionParameterRequest'
  Luna.Marketplace.Public.Client.MarketplaceSubscriptionParameterRequest:
    required:
      - name
      - type
      - value
      - isSystemParameter
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      value:
        type: string
      isSystemParameter:
        type: boolean
  Luna.Marketplace.Public.Client.MarketplaceParameter:
    required:
      - ParameterName
      - DisplayName
      - Description
      - ValueType
    type: object
    properties:
      ParameterName:
        type: string
      DisplayName:
        type: string
      Description:
        type: string
      ValueType:
        type: string
      FromList:
        type: boolean
      ValueList:
        type: string
      Maximum:
        format: int32
        type: integer
      Minimum:
        format: int32
        type: integer
      IsRequired:
        type: boolean
      isUserInput:
        type: boolean
      defaultValue:
        type: object
  Luna.Gallery.Public.Client.PublishedLunaApplication:
    required:
      - UniqueName
      - DisplayName
      - Description
      - Publisher
      - Tags
    type: object
    properties:
      UniqueName:
        type: string
      DisplayName:
        type: string
      Description:
        type: string
      LogoImageUrl:
        type: string
      DocumentationUrl:
        type: string
      Publisher:
        type: string
      Tags:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaPublishedApplicationTag'
      Details:
        $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationDetails'
    example:
      UniqueName: mylunaapp
      DisplayName: My Luna App
      Description: This is my Luna app
      LogoImageUrl: https://aka.ms/lunalog.png
      DocumentationUrl: https://aka.ms/lunadoc
      Publisher: Microsoft
      Tags: [ ]
      Details:
        APIs: [ ]
  Luna.Gallery.Public.Client.LunaPublishedApplicationTag:
    type: object
    properties:
      Name:
        type: string
      Value:
        type: string
  Luna.Gallery.Public.Client.LunaApplicationDetails:
    type: object
    properties:
      APIs:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaAPIDetails'
  Luna.Gallery.Public.Client.LunaAPIDetails:
    type: object
    properties:
      Name:
        type: string
      Type:
        type: string
      Versions:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaAPIVersionDetails'
  Luna.Gallery.Public.Client.LunaAPIVersionDetails:
    type: object
    properties:
      Name:
        type: string
      Operations:
        type: array
        items:
          type: string
  Luna.Gallery.Public.Client.LunaApplicationSwagger:
    type: object
    properties:
      APIs:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaAPIDetails'
  Luna.Gallery.Public.Client.LunaApplicationSubscription:
    required:
      - SubscriptionId
      - SubscriptionName
    type: object
    properties:
      SubscriptionId:
        format: uuid
        type: string
        example: 00000000-0000-0000-0000-000000000000
      SubscriptionName:
        type: string
      PrimaryKey:
        type: string
      SecondaryKey:
        type: string
      BaseUrl:
        type: string
      Notes:
        type: string
      Owners:
        type: array
        items:
          $ref: '#/definitions/Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner'
      CreatedTime:
        format: date-time
        type: string
    example:
      SubscriptionId: 0eb1e9dd-df4e-4b03-9e8f-6d8ac0eab782
      SubscriptionName: mysub
      PrimaryKey: 60158cd36c464531bf40a6c7efc629cd
      SecondaryKey: fc7cfaab23b0494aa53f178f7fbc720c
      BaseUrl: https://luna.azurewebapp.net/api
      Notes: this is my subscription
      Owners:
        - UserId: c4627f84-c3a8-45b3-8709-565bd2e50b97
          UserName: FirstName LastName
      CreatedTime: '2021-06-10T18:00:30.1320267-07:00'
  Luna.Gallery.Public.Client.LunaApplicationSubscriptionOwner:
    required:
      - UserId
    type: object
    properties:
      UserId:
        type: string
      UserName:
        type: string
    example:
      UserId: 2d88c6a1-8ece-49e8-8b23-673c6a4272d2
      UserName: FirstName LastName
  Luna.Gallery.Public.Client.LunaApplicationSubscriptionKeys:
    required:
      - PrimaryKey
      - SecondaryKey
    type: object
    properties:
      PrimaryKey:
        type: string
      SecondaryKey:
        type: string
    example:
      PrimaryKey: 3cbeda43ef6b4dc0b61220fbb2f7dda4
      SecondaryKey: fc7cfaab23b0494aa53f178f7fbc720c
  Luna.Gallery.Public.Client.LunaApplicationSubscriptionNotes:
    required:
      - Notes
    type: object
    properties:
      Notes:
        type: string
    example:
      Notes: this is my subscription
  Luna.Gallery.Public.Client.ApplicationPublisher:
    required:
      - Name
      - DisplayName
      - Type
      - Description
      - IsEnabled
    type: object
    properties:
      Name:
        type: string
      DisplayName:
        type: string
      Type:
        type: string
      Description:
        type: string
      EndpointUrl:
        type: string
      WebsiteUrl:
        type: string
      IsEnabled:
        type: boolean
      PublisherKey:
        type: string
      CreatedTime:
        format: date-time
        type: string
      LastUpdatedTime:
        format: date-time
        type: string
    example:
      Name: ace
      DisplayName: ACE team
      Type: Internal
      Description: Azure Customer Engineering Team
      EndpointUrl: https://aka.ms/aceendpoint
      WebsiteUrl: https://aka.ms/acewebsite
      IsEnabled: true
      PublisherKey: publisher-key
      CreatedTime: 
      LastUpdatedTime: 
securityDefinitions:
  x-functions-key:
    type: apiKey
    name: x-functions-key
    in: header
    description: Azure function key
  http-bearer: { }