swagger: '2.0'
info:
  title: Luna.Publish.Functions
  version: V1
host: localhost:7071
schemes:
  - http
paths:
  '/api/reviewsettings/webhooks/{name}':
    put:
      tags:
        - Review Settings
      summary: Create an automation webhook
      operationId: putApiReviewsettingsWebhooksByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the webhook
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.AutomationWebhook'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.AutomationWebhook'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - Review Settings
      summary: Update an automation webhook
      operationId: patchApiReviewsettingsWebhooksByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the automation webhook
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.AutomationWebhook'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.AutomationWebhook'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - Review Settings
      summary: Delete an automation webhook
      operationId: deleteApiReviewsettingsWebhooksByName
      parameters:
        - in: path
          name: name
          description: Name of the automation webhook
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
    get:
      tags:
        - Review Settings
      summary: Get an automation webhook
      operationId: getApiReviewsettingsWebhooksByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the automation webhook
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.AutomationWebhook'
      security:
        - x-functions-key: [ ]
  /api/reviewsettings/webhooks:
    get:
      tags:
        - Application Review
      summary: List automation webhooks
      operationId: getApiReviewsettingsWebhooks
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Publish.Public.Client.AutomationWebhook'
            example:
              Name: responsible-ai-scan
              Description: Check responsible AI
              WebhookUrl: https://aka.ms/lunaresponsibleai
              IsEnabled: true
              CreatedTime: 
              LastUpdatedTime: 
      security:
        - x-functions-key: [ ]
  '/api/marketplace/offers/{offerId}':
    delete:
      tags:
        - Azure Marketplace
      summary: Delete an Azure Marketplace SaaS offer
      operationId: deleteApiMarketplaceOffersByOfferId
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/marketplace/offers/{offerId}/publish':
    post:
      tags:
        - Azure Marketplace
      summary: Publish an Azure Marketplace SaaS offer
      operationId: postApiMarketplaceOffersByOfferIdPublish
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/marketplace/offers/{offerId}/plans/{planId}':
    put:
      tags:
        - Azure Marketplace
      summary: Create a plan in an Azure Marketplace SaaS offer
      operationId: putApiMarketplaceOffersByOfferIdPlansByPlanId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
        - in: path
          name: planId
          description: Id of marketplace SaaS plan
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - Azure Marketplace
      summary: Update a plan in an Azure Marketplace SaaS offer
      operationId: patchApiMarketplaceOffersByOfferIdPlansByPlanId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
        - in: path
          name: planId
          description: Id of marketplace SaaS plan
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - Azure Marketplace
      summary: Delete a plan in an Azure Marketplace SaaS offer
      operationId: deleteApiMarketplaceOffersByOfferIdPlansByPlanId
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
        - in: path
          name: planId
          description: Id of marketplace SaaS plan
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
    get:
      tags:
        - Azure Marketplace
      summary: Get a plan in an Azure Marketplace SaaS offer
      operationId: getApiMarketplaceOffersByOfferIdPlansByPlanId
      produces:
        - application/json
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
        - in: path
          name: planId
          description: Id of marketplace SaaS plan
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      security:
        - x-functions-key: [ ]
  '/api/marketplace/offers/{offerId}/plans':
    get:
      tags:
        - Azure Marketplace
      summary: List plans in an Azure Marketplace SaaS offer
      operationId: getApiMarketplaceOffersByOfferIdPlans
      produces:
        - application/json
      parameters:
        - in: path
          name: offerId
          description: Id of marketplace SaaS offer
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      security:
        - x-functions-key: [ ]
  /api/applicationss:
    get:
      tags:
        - Application
      summary: List all applications
      operationId: getApiApplicationss
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplication'
      security:
        - x-functions-key: [ ]
  '/api/applicationss/{name}/masterkeys':
    get:
      tags:
        - Application
      summary: Get Luna application master keys
      operationId: getApiApplicationssByNameMasterkeys
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: The name of the application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationMasterKeys'
      security:
        - x-functions-key: [ ]
  '/api/applications/{name}':
    get:
      tags:
        - Application
      summary: Get a Luna application
      operationId: getApiApplicationsByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: The name of the application
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplication'
      security:
        - x-functions-key: [ ]
    put:
      tags:
        - Application
      summary: Create a Luna application
      operationId: putApiApplicationsByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationProp'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationProp'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - Application
      summary: Update a Luna application
      operationId: patchApiApplicationsByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationProp'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationProp'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - Application
      summary: Delete a Luna application
      operationId: deleteApiApplicationsByName
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/applications/{name}/regenerateMasterKeys':
    post:
      tags:
        - Application
      summary: Regenerate Luna application master keys
      operationId: postApiApplicationsByNameRegenerateMasterKeys
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
        - in: query
          name: key-name
          description: The key name. Valid values are PrimaryKey or SecondaryKey
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationMasterKeys'
      security:
        - x-functions-key: [ ]
  '/api/applications/{name}/publish':
    post:
      tags:
        - Application
      summary: Publish a Luna application
      operationId: postApiApplicationsByNamePublish
      parameters:
        - in: path
          name: name
          description: Name of Luna application
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/apis/{apiName}':
    put:
      tags:
        - API
      summary: Create an API in the specified Luna application
      operationId: putApiApplicationsByAppNameApisByApiName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: apiName
          description: Name of API
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseLunaAPIProp'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseLunaAPIProp'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - API
      summary: Update an API in the specified Luna application
      operationId: patchApiApplicationsByAppNameApisByApiName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: apiName
          description: Name of API
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseLunaAPIProp'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseLunaAPIProp'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - API
      summary: Delete an API from the specified Luna application
      operationId: deleteApiApplicationsByAppNameApisByApiName
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: apiName
          description: Name of API
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  '/api/applications/{appName}/apis/{apiName}/versions/{versionName}':
    put:
      tags:
        - API Version
      summary: Create a version in the specified API
      operationId: putApiApplicationsByAppNameApisByApiNameVersionsByVersionName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: apiName
          description: Name of API
          required: true
          type: string
        - in: path
          name: versionName
          description: Name of API version
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseAPIVersionProp'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseAPIVersionProp'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - API Version
      summary: Update a version in the specified API
      operationId: patchApiApplicationsByAppNameApisByApiNameVersionsByVersionName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: apiName
          description: Name of API
          required: true
          type: string
        - in: path
          name: versionName
          description: Name of API version
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseAPIVersionProp'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Publish.Public.Client.BaseAPIVersionProp'
      security:
        - x-functions-key: [ ]
    delete:
      tags:
        - s
      summary: Delete a version from the specified API
      operationId: deleteApiApplicationsByAppNameApisByApiNameVersionsByVersionName
      parameters:
        - in: path
          name: appName
          description: Name of Luna application
          required: true
          type: string
        - in: path
          name: apiName
          description: Name of API
          required: true
          type: string
        - in: path
          name: versionName
          description: Name of API version
          required: true
          type: string
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
definitions:
  Luna.Publish.Public.Client.AutomationWebhook:
    required:
      - Name
      - Description
      - WebhookUrl
      - IsEnabled
    type: object
    properties:
      Name:
        type: string
      Description:
        type: string
      WebhookUrl:
        type: string
      IsEnabled:
        type: boolean
      CreatedTime:
        format: date-time
        type: string
      LastUpdatedTime:
        format: date-time
        type: string
    example:
      Name: responsible-ai-scan
      Description: Check responsible AI
      WebhookUrl: https://aka.ms/lunaresponsibleai
      IsEnabled: true
      CreatedTime: 
      LastUpdatedTime: 
  Luna.Publish.Public.Client.MarketplaceOffer:
    required:
      - OfferId
      - Properties
      - Plans
      - Parameters
    type: object
    properties:
      OfferId:
        type: string
      Status:
        type: string
      Properties:
        $ref: '#/definitions/Luna.Publish.Public.Client.MarketplaceOfferProp'
      Plans:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlan'
      Parameters:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.MarketplaceParameter'
      ProvisioningSteps:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.MarketplaceProvisioningStep'
      ProvisioningStepsSecretName:
        type: string
  Luna.Publish.Public.Client.MarketplaceOfferProp:
    required:
      - DisplayName
      - Description
    type: object
    properties:
      DisplayName:
        type: string
      Description:
        type: string
      IsManualActivation:
        type: boolean
  Luna.Publish.Public.Client.MarketplacePlan:
    required:
      - PlanId
      - Parameters
    type: object
    properties:
      PlanId:
        type: string
      Properties:
        $ref: '#/definitions/Luna.Publish.Public.Client.MarketplacePlanProp'
      Parameters:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.MarketplaceParameter'
  Luna.Publish.Public.Client.MarketplacePlanProp:
    required:
      - Description
      - Mode
    type: object
    properties:
      Description:
        type: string
      Mode:
        type: string
      OnSubscribe:
        type: array
        items:
          type: string
      OnUpdate:
        type: array
        items:
          type: string
      OnSuspend:
        type: array
        items:
          type: string
      OnDelete:
        type: array
        items:
          type: string
      OnPurge:
        type: array
        items:
          type: string
  Luna.Publish.Public.Client.MarketplaceParameter:
    required:
      - ParameterName
      - DisplayName
      - Description
      - ValueType
    type: object
    properties:
      ParameterName:
        type: string
      DisplayName:
        type: string
      Description:
        type: string
      ValueType:
        type: string
      FromList:
        type: boolean
      ValueList:
        type: string
      Maximum:
        format: int32
        type: integer
      Minimum:
        format: int32
        type: integer
      IsRequired:
        type: boolean
  Luna.Publish.Public.Client.MarketplaceProvisioningStep:
    required:
      - Name
      - Type
      - Properties
    type: object
    properties:
      Name:
        type: string
      Type:
        type: string
      Properties:
        $ref: '#/definitions/Luna.Publish.Public.Client.BaseProvisioningStepProp'
  Luna.Publish.Public.Client.BaseProvisioningStepProp:
    required:
      - IsSynchronized
      - Description
    type: object
    properties:
      IsSynchronized:
        type: boolean
      Description:
        type: string
  Luna.Publish.Public.Client.LunaApplication:
    required:
      - Name
      - Status
      - APIs
    type: object
    properties:
      Name:
        type: string
      Status:
        type: string
      Properties:
        $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationProp'
      APIs:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.LunaAPI'
  Luna.Publish.Public.Client.LunaApplicationProp:
    required:
      - DisplayName
      - Description
      - DocumentationUrl
      - LogoImageUrl
      - Publisher
      - Tags
    type: object
    properties:
      OwnerUserId:
        type: string
      DisplayName:
        type: string
      Description:
        type: string
      DocumentationUrl:
        type: string
      LogoImageUrl:
        type: string
      Publisher:
        type: string
      Tags:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.LunaApplicationTag'
      CreatedBy:
        type: string
      PrimaryMasterKeySecretName:
        type: string
      SecondaryMasterKeySecretName:
        type: string
    example:
      OwnerUserId: 43ebb35e-be1a-4dbf-92da-fb8a069d6a2c
      DisplayName: My App
      Description: This is my application
      DocumentationUrl: https://aka.ms/lunadoc
      LogoImageUrl: https://aka.ms/lunalogo.png
      Publisher: Microsoft
      Tags:
        - Key: Department
          Value: HR
      CreatedBy: 
      PrimaryMasterKeySecretName: 
      SecondaryMasterKeySecretName: 
  Luna.Publish.Public.Client.LunaApplicationTag:
    type: object
    properties:
      Key:
        type: string
      Value:
        type: string
  Luna.Publish.Public.Client.LunaAPI:
    type: object
    properties:
      Name:
        type: string
      Properties:
        $ref: '#/definitions/Luna.Publish.Public.Client.BaseLunaAPIProp'
      Versions:
        type: array
        items:
          $ref: '#/definitions/Luna.Publish.Public.Client.APIVersion'
  Luna.Publish.Public.Client.BaseLunaAPIProp:
    required:
      - DisplayName
      - Type
      - Description
    type: object
    properties:
      DisplayName:
        type: string
      Type:
        type: string
      Description:
        type: string
      AdvancedSettings:
        type: string
    example:
      DisplayName: sentimentanalysis
      Type: Pipeline
      Description: Sentiment analysis API
      AdvancedSettings: 
  Luna.Publish.Public.Client.APIVersion:
    type: object
    properties:
      Name:
        type: string
      Properties:
        $ref: '#/definitions/Luna.Publish.Public.Client.BaseAPIVersionProp'
  Luna.Publish.Public.Client.BaseAPIVersionProp:
    required:
      - Type
      - Description
    type: object
    properties:
      Type:
        type: string
      Description:
        type: string
      AdvancedSettings:
        type: string
    example:
      Type: AzureML
      Description: API version from Azure ML workspace
      AdvancedSettings: 
  Luna.Publish.Public.Client.LunaApplicationMasterKeys:
    required:
      - PrimaryMasterKey
      - SecondaryMasterKey
    type: object
    properties:
      PrimaryMasterKey:
        type: string
      SecondaryMasterKey:
        type: string
    example:
      PrimaryMasterKey: 92d3dd2a428540e7871aee92af26fc7d
      SecondaryMasterKey: 60158cd36c464531bf40a6c7efc629cd
securityDefinitions:
  x-functions-key:
    type: apiKey
    name: x-functions-key
    in: header
    description: Azure function key