swagger: '2.0'
info:
  title: Luna.RBAC.Functions
  version: V1
host: localhost:7071
schemes:
  - http
paths:
  /api/roleassignments:
    get:
      tags:
        - Role Assignment
      summary: List role assignments
      operationId: getApiRoleassignments
      produces:
        - application/json
      responses:
        '200':
          description: Request contract
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.RBAC.Public.Client.RoleAssignmentRequest'
            example:
              Uid: b46324b3-6a92-4e35-84be-fa1b2919af69
              UserName: FirstName LastName
              Role: SystemAdmin
              CreatedTime: '0001-01-01T00:00:00.0000000-08:00'
      security:
        - x-functions-key: [ ]
  /api/roleassignments/add:
    post:
      tags:
        - Role Assignment
      summary: Add role assignment
      operationId: postApiRoleassignmentsAdd
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.RoleAssignmentRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.RoleAssignmentResponse'
      security:
        - x-functions-key: [ ]
  /api/roleassignments/remove:
    post:
      tags:
        - Role Assignment
      summary: Remove role assignment
      operationId: postApiRoleassignmentsRemove
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.RoleAssignmentRequest'
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  /api/ownership/add:
    post:
      tags:
        - Ownership
      summary: Assign ownership
      operationId: postApiOwnershipAdd
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.OwnershipRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.OwnershipResponse'
      security:
        - x-functions-key: [ ]
  /api/ownership/remove:
    post:
      tags:
        - Ownership
      summary: Remove ownership
      operationId: postApiOwnershipRemove
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.OwnershipRequest'
      responses:
        '204':
          description: Success
      security:
        - x-functions-key: [ ]
  /api/canaccess:
    post:
      tags:
        - Access Control
      summary: Check if a user can access the specified resource and action
      operationId: postApiCanaccess
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.RBACQueryRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.RBAC.Public.Client.RBACQueryResultResponse'
      security:
        - x-functions-key: [ ]
definitions:
  Luna.RBAC.Public.Client.RoleAssignmentRequest:
    required:
      - Uid
      - UserName
      - Role
    type: object
    properties:
      Uid:
        type: string
      UserName:
        type: string
      Role:
        type: string
      CreatedTime:
        format: date-time
        type: string
    example:
      Uid: b46324b3-6a92-4e35-84be-fa1b2919af69
      UserName: FirstName LastName
      Role: SystemAdmin
      CreatedTime: '0001-01-01T00:00:00.0000000-08:00'
  Luna.RBAC.Public.Client.RoleAssignmentResponse:
    required:
      - Uid
      - UserName
      - Role
    type: object
    properties:
      Uid:
        type: string
      UserName:
        type: string
      Role:
        type: string
      CreatedTime:
        format: date-time
        type: string
    example:
      Uid: b46324b3-6a92-4e35-84be-fa1b2919af69
      UserName: FirstName LastName
      Role: SystemAdmin
      CreatedTime: '0001-01-01T00:00:00.0000000-08:00'
  Luna.RBAC.Public.Client.OwnershipRequest:
    required:
      - Uid
      - ResourceId
    type: object
    properties:
      Uid:
        type: string
      ResourceId:
        type: string
      CreatedTime:
        format: date-time
        type: string
    example:
      Uid: fcd14a2a-31d3-49c1-9e1b-39063da1ac6a
      ResourceId: applications/myapp
      CreatedTime: '0001-01-01T00:00:00.0000000-08:00'
  Luna.RBAC.Public.Client.OwnershipResponse:
    required:
      - Uid
      - ResourceId
    type: object
    properties:
      Uid:
        type: string
      ResourceId:
        type: string
      CreatedTime:
        format: date-time
        type: string
    example:
      Uid: fcd14a2a-31d3-49c1-9e1b-39063da1ac6a
      ResourceId: applications/myapp
      CreatedTime: '0001-01-01T00:00:00.0000000-08:00'
  Luna.RBAC.Public.Client.RBACQueryRequest:
    required:
      - Uid
      - ResourceId
    type: object
    properties:
      Uid:
        type: string
      ResourceId:
        type: string
      Action:
        type: string
    example:
      Uid: b46324b3-6a92-4e35-84be-fa1b2919af69
      ResourceId: applications/myapp
      Action: 
  Luna.RBAC.Public.Client.RBACQueryResultResponse:
    required:
      - Query
      - CanAccess
    type: object
    properties:
      Query:
        $ref: '#/definitions/Luna.RBAC.Public.Client.RBACQueryRequest'
      CanAccess:
        type: boolean
      Role:
        type: string
    example:
      Query:
        Uid: b46324b3-6a92-4e35-84be-fa1b2919af69
        ResourceId: applications/myapp
        Action: 
      CanAccess: true
      Role: Admin
securityDefinitions:
  x-functions-key:
    type: apiKey
    name: x-functions-key
    in: header
    description: Azure function key